title: wxblog
author: Mohamed Ashraf Wx
tagline: Personal Arabic Blog 
description: A personal space to share my thoughts.
iconURL: favicon.ico
remote-theme: tarekeldeeb/arabic-blog-green-dark-theme

# for a clean URL
permalink: :slug

social:
  github: mohamedashraf-eng
  linkedin: mohamed-ashraf-wx

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      image: assets/avatar.png

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-gist

### comments & analytics
#hyvor_talk_website_id: 3992
google_analytics: G-XXXXXXXXXX
